# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LineInformList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=35)),
                ('bank', models.CharField(max_length=4)),
                ('BS', models.CharField(max_length=1)),
                ('ccy', models.CharField(max_length=3)),
                ('exrate', models.FloatField(default=0.0)),
                ('stoptoday', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LineUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=35)),
                ('token', models.CharField(default='', max_length=45)),
                ('profilesrc', models.CharField(default='', max_length=80)),
                ('msgcnt', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='oper_para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
