# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuserinfo',
            name='profilesrc',
            field=models.CharField(default='', max_length=160),
        ),
    ]
